---
name: GD-SecurityImage
version: 1.582
author:
  - Burak Gursoy <burak@cpan.org>
abstract: Security image (captcha) generator.
license: perl
requires:
  GD: 0
recommends:
  Image::Magick: 6.0.4
provides:
  GD::SecurityImage:
    file: lib/GD/SecurityImage.pm
    version: 1.582
  GD::SecurityImage::AC:
    file: lib/GD/SecurityImage/AC.pm
    version: 1.02
  GD::SecurityImage::GD:
    file: lib/GD/SecurityImage/GD.pm
    version: 1.48
  GD::SecurityImage::Magick:
    file: lib/GD/SecurityImage/Magick.pm
    version: 1.36
  GD::SecurityImage::Styles:
    file: lib/GD/SecurityImage/Styles.pm
    version: 1.12
generated_by: Module::Build version 0.2611
